services:
  app:
    build: .
    container_name: hello-go-app
    ports:
      - "8080:8080"
    depends_on:
      - jaeger

  jaeger:
    # Pinning to a specific recent version for stability
    image: jaegertracing/all-in-one:1.54
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "14317:14317" # OTLP gRPC
    # This command explicitly enables the OTLP receiver via command-line flags
    command:
      - --collector.otlp.enabled=true
      - --collector.otlp.grpc.host-port=:14317